name: Build OpenJFX

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-22.04"

    steps:
      - name: Checkout builder repo
        uses: actions/checkout@v4
      - name: Install GCC 13
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
      - name: Install dependencies
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install ant libgl1-mesa-dev libx11-dev libxxf86vm-dev libxt-dev pkg-config libgtk2.0-dev libgtk-3-dev libxtst-dev libasound2-dev libcups2-dev
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13
      - name: Set up JDK 24
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
      - name: Clone OpenJDK Mobile sources 
        run: |
          git clone https://github.com/openjdk/mobile.git
          cd mobile
          patch -p1 <../openjdk-ext/src/jfx.patch
          cd ..
      - name: Clone OpenJFX
        run: |
          git clone https://github.com/openjdk/jfx.git
          cd jfx
          sh gradlew shadersClasses
          cd ..
          cd mobile
          sh configure --with-conf-name=jfx --with-openjfx-modules=../jfx --disable-warnings-as-errors
          cd build/jfx
          make images
          cd images
          ls -l ../../../../
          zip -r ../../../../openjdk-jfx-linux-x86_64.zip jdk

      - name: Create snapshot release 
        uses: softprops/action-gh-release@v2
        with:
          name: "Snapshot release"
          tag_name: snapshot
          prerelease: true
          files: |
            openjdk-jfx-linux-x86_64.zip


